export const FETCH_CRYPTO_DATA = 'FETCH_CRYPTO_DATA';
export const FETCH_CRYPTO_DATA_SUCCESS = 'FETCH_CRYPTO_DATA_SUCCESS';
export const FETCH_CRYPTO_DATA_FAILED = 'FETCH_CRYPTO_DATA_FAILED';

export const FETCH_CRYPTO_NEWS = 'FETCH_CRYPTO_NEWS';
export const FETCH_CRYPTO_NEWS_SUCCESS = 'FETCH_CRYPTO_NEWS_SUCCESS';
export const FETCH_CRYPTO_NEWS_FAILED = 'FETCH_CRYPTO_NEWS_FAILED';